export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

